[pyprland]
plugins = ["scratchpads","lost_windows","expose"]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"
