#!/bin/sh
gpu_type=$(envycontrol -q)
echo "$gpu_type"
if [ "$gpu_type" = "hybrid" ]; then
    # export WLR_NO_HARDWARE_CURSORS=1
    export MOZ_USE_XINPUT2=1
    export MOZ_DBUS_REMOTE=1
    export __GL_GSYNC_ALLOWED=0
    export __GL_VRR_ALLOWED=0
    export GDK_BACKEND=wayland
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
    export MOZ_ENABLE_WAYLAND=1
    export QT_QPA_PLATFORM=wayland
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=sway
    export WLR_NO_HARDWARE_CURSORS=1
    export WLR_DRM_NO_ATOMIC=1
    /usr/bin/sway --unsupported-gpu
elif [ "$gpu_type" = "nvidia" ]; then
    export WLR_DRM_NO_ATOMIC=1
    export MOZ_USE_XINPUT2=1
    export MOZ_DBUS_REMOTE=1
    export GBM_BACKEND=nvidia-drm
    export __GL_GSYNC_ALLOWED=0
    export __GL_VRR_ALLOWED=0
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export GDK_BACKEND=wayland
    export QT_AUTO_SCREEN_SCALE_FACTOR=1
    export MOZ_ENABLE_WAYLAND=1
    export QT_QPA_PLATFORM=wayland
    export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
    export XDG_SESSION_TYPE=wayland
    export XDG_CURRENT_DESKTOP=sway
    export GBM_BACKEND=nvidia-drm
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export WLR_NO_HARDWARE_CURSORS=1
    export LIBVA_DRIVER_NAME=nvidia
    /usr/bin/sway --unsupported-gpu
elif [ "$gpu_type" = "integrated" ]; then
    export MOZ_ENABLE_WAYLAND=1
    export MOZ_USE_XINPUT2=1
    export MOZ_DBUS_REMOTE=1
    /usr/bin/sway
fi
