#!/bin/sh
output = $(swaymsg -t get_tree | jq '.nodes[] | select(.name | test ("^_;") | not).name')
if grep -q open /proc/acpi/button/lid/LID0/state; then
    swaymsg output $output enable
else
    swaymsg output $output disable
fi
