#!/bin/bash

entries="output\narea\nwindow\nactive\nsave\nedit"

save_entries="output\narea\nwindow\nactive"
edit_entries="output\narea\nwindow\nactive"
selected=$(echo -e "$entries" | wofi --show=dmenu)

case $selected in
    "output")
        grimshot --wait 1 copy output;;
    "area")
        grimshot --wait 1 copy area;;
    "window")
        grimshot --wait 1 copy window;;
    "active")
        grimshot --wait 1 copy active;;
    "save")
        save_selected=$(echo -e "$save_entries" | wofi --show=dmenu)
        case $save_selected in
            "output")
                grimshot --wait 1 save output;;
             "area")
                grimshot --wait 1 save area;;
            "window")
                grimshot --wait 1 save window;;
            "active")
                grimshot --wait 1 save active;;
        esac
    ;;
    "edit")
        edit_selected=$(echo -e "$edit_entries" | wofi --show=dmenu)
        case $edit_selected in
            "output")
                grimshot --wait 1 save output - | swappy -f - ;;
            "area")
                grimshot --wait 1 save area - | swappy -f - ;;
            "window")
                grimshot --wait 1 save window - | swappy -f - ;;
            "active")
                grimshot --wait 1 save active - | swappy -f - ;;
        esac
    ;;
esac
