#!/bin/bash

entries="output\narea\nwindow\nactive\nsave\nedit"

save_entries="output\narea\nwindow\nactive"
edit_entries="output\narea\nwindow\nactive"
selected=$(echo -e "$entries" | wofi --show=dmenu)

case $selected in
    "output")
        grimshot  --notify  copy output;;
    "area")
        grimshot  --notify copy area;;
    "window")
        grimshot  --notify copy window;;
    "active")
        grimshot  --notify copy active;;
    "save")
        save_selected=$(echo -e "$save_entries" | wofi --show=dmenu)
        case $save_selected in
            "output")
                grimshot  --notify save output;;
             "area")
                grimshot  --notify save area;;
            "window")
                grimshot  --notify save window;;
            "active")
                grimshot  --notify save active;;
        esac
    ;;
    "edit")
        edit_selected=$(echo -e "$edit_entries" | wofi --show=dmenu)
        case $edit_selected in
            "output")
                grimshot  --notify save output - | swappy -f - ;;
            "area")
                grimshot  --notify save area - | swappy -f - ;;
            "window")
                grimshot  --notify save window - | swappy -f - ;;
            "active")
                grimshot  --notify save active - | swappy -f - ;;
        esac
    ;;
esac
